# Generated by Django 5.1.5 on 2025-01-31 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0003_userprofile_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_confirmed',
        ),
    ]
